dist: xenial # required for Python >= 3.7
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
# command to install dependencies
install:
  - pip install pipenv
  - pipenv install --dev
# command to run tests
script: pipenv run pytest --cov=src test/
after_success:
  - pipenv run coveralls
